<?php
/**
 * @file
 * cms_core_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function cms_core_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Powerstart Homepage: Long page',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '920a03e5-81f0-4ab6-8a15-b83e77e67ba2',
  'type' => 'page',
  'language' => 'und',
  'created' => 1418031352,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd6b1dd5c-9212-4468-9a64-e6e674ca32b7',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2 style="text-align: center;">&nbsp;</h2>

<h2 style="text-align: center;">Build your Drupal Site In Minutes With CMS Powerstart!</h2>

<p class="lead" style="text-align: center;">CMS Powerstart makes it a frictionless and pleasurable experience to install and customize a Drupal CMS site</p>

<p class="lead" style="text-align: center;">&nbsp;</p>

<hr>
<p><img alt="" src="http://i.imgur.com/YzCKSJk.jpg" style="width: 100%;"></p>

<p>&nbsp;</p>

<h1 style="text-align: center;">CMS Powerstart Improves The Drupal Experience</h1>

<p>&nbsp;</p>

<p style="text-align: center;">[lead]CMS Powerstart is an open source Drupal distribution that aims to improve the Drupal experience for everyone, especially in small business website projects.[/lead]</p>

<p>[row]</p>

<p>[column sm="4"]</p>

<p>[box heading="Fast" icon="fighter-jet" layout="icon-boxed" icon_size="4x"]CMS Powerstart is all about saving you time in getting your Drupal project done. The turn-key CMS components can save you many hours of configuration for common CMS features.[/box]</p>

<p>[/column]</p>

<p>[column sm="4"]</p>

<p>[box heading="Easy" icon="smile-o" layout="icon-boxed" icon_size="4x"]The idea behind CMS Powerstart is to allow anyone to build a website, without having to learn how to code. You can point and click your way to a powerful responsive CMS website![/box]</p>

<p>[/column]</p>

<p>[column sm="4"]</p>

<p>[box heading="Drupal" icon="drupal" layout="icon-boxed" icon_size="4x" icon_color="#<span style="color: rgb(34, 34, 34); font-family: \'Lucida Grande\', \'DejaVu Sans\', \'Bitstream Vera Sans\', Verdana, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.9999942779541px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">0077c0</span>"]CMS Powerstart is not a Drupal fork! It\'s 100% Drupal, it can work with any Drupal module or theme. Powerstart is continuously improved by the Drupal community![/box]</p>

<p>[/column]</p>

<p>[/row]</p>

<p>&nbsp;</p>

<h2 style="text-align: center;">Main Features</h2>

<p class="lead" style="text-align: center;">Our easy to use theme options, shortcodes and unique elements allow you to create any type of website.</p>

<p>[row]</p>

<p>[column md="4"]</p>

<p>[lead]Natively Responsive![/lead]</p>

<p>Thanks to the Bootstrap 3 based approach CMS Powerstart works magnificently on any device!</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]Simplicity[/lead]</p>

<p>Ready-made WYSIWYG and advanced features. Save many hours of configuration and research!</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]Flexibility[/lead]</p>

<p>CMS Powerstart is designed to be extendible. Drupal APIs and best practices are used throughout!</p>

<p>[/column]</p>

<p>[/row]</p>

<p>[row]</p>

<p>[column md="4"]</p>

<p>[lead]Customizable[/lead]</p>

<p>Using the custom build interface you can select the features that matter to you. No code bloat!</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]SEO Optimized[/lead]</p>

<p>We studies Wordpress and Yoast resources to create a Drupal configuration that ranks at the top!</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]Bootstrap 3[/lead]</p>

<p>Like Bootstrap? You will love the complete Bootstrap 3 integration in shortcodes, views, field classes and image styles!</p>

<p>[/column]</p>

<p>[/row]</p>

<p>[row]</p>

<p>[column md="4"]</p>

<p>[lead]WYSIWYG Included![/lead]</p>

<p>WYSIWYG is hard in Drupal! We researched and created a complete solution using CKEditor 4.</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]Shortcodes[/lead]</p>

<p>Shortcodes allow you to create rich responsive content, with retina icons, Bootstrap 3 components and more.</p>

<p>[/column]</p>

<p>[column md="4"]</p>

<p>[lead]Drupal Community[/lead]</p>

<p>CMS Powerstart is not a fork! It\'s 100% Drupal, so you can extend it with any existing modules, themes and libraries!</p>

<p>[/column]</p>

<p>[/row]</p>

<p>&nbsp;</p>

<hr>
<h2 style="text-align: center;">&nbsp;</h2>

<h2 style="text-align: center;">More features</h2>

<p>&nbsp;</p>

<p>[row]</p>

<p>[column md="4"]</p>

<ul class="lead">
	<li>Easy to extend</li>
	<li>Drupal 8 code architecture</li>
	<li>Demo content included</li>
	<li>Pagespeed optimized</li>
	<li>HTML5 SEO Optimized</li>
</ul>

<p>[/column]</p>

<p>[column md="4"]</p>

<ul class="lead">
	<li>Bootstrap 3 field API</li>
	<li>Bootstrap 3 shortcodes</li>
	<li>Bootstrap 3 block classes</li>
	<li>Bootstrap 3 views</li>
	<li>Bootstrap 3 image styles</li>
</ul>

<p>[/column]</p>

<p>[column md="4"]</p>

<ul class="lead">
	<li>Fully loaded WYSIWYG</li>
	<li>Advanced CMS Components</li>
	<li>Custom build interface</li>
	<li>Can work with any theme</li>
	<li>Awesome shortcode elements</li>
</ul>

<p>[/column]</p>

<p style="text-align: center;clear:both">[button type="primary" size="lg" link="http://www.sooperthemes.com/minisites/drupal-cms-powerstart-custom" xclass="center-block col-sm-2 clear-both"]CMS Powerstart Download[/button]</p>

<p>[/row]</p>

<p>&nbsp;</p>

<hr>
<p>&nbsp;</p>

<p>[row]</p>

<p>[column sm="9"]</p>

<h4>Responsive content? No problem</h4>

<p>With CMS Powerstart and its Bootstrap3 integration resonsive layouts and content are super easy.</p>

<p>CMS Powerstart is responsive to the core, and the responsive system is used throughout: in the design, in the views, in the content, everywhere!</p>

<p>[row]</p>

<p>[column md="6"]</p>

<p>Nested columns are not a problem with CMS Powerstart. Rows and columns can be nested limitlessly, keeping the flexibility of Bootstraps device shortcuts (large, medium, small, xsmall).</p>

<p>[/column][column md="6"]</p>

<p>The 12 column grid system is divisible by 3 and 4, allowing you to easily create the most common layouts. Pull and push classes give you full control over your design.</p>

<p>[/column]</p>

<p>[/row]</p>

<p>[/column]</p>

<p>[column sm="3"]<img alt="" src="http://i.imgur.com/ln0LQPw.jpg">[/column]</p>

<p>[/row]</p>

<p>&nbsp;</p>

<hr>
<h3>&nbsp;</h3>

<h3>CMS Powerstart is developed by SooperThemes with end-users in mind</h3>

<p>[lead]The includes website editors, marketing staff, site builders and other users who contribute to the success of your website. Drupal is great for developers and produces great result for your site\'s visitors but the other people who add value to your site are not always as well catered. CMS Powerstart aims to change this by offering awesome tools to create rich, organized content.[/lead]</p>

<p>[row]</p>

<p>[column sm="6"]</p>

<p>[block module:bean delta:facebook-widget]</p>

<p>[/column]</p>

<p>[column sm="6"]</p>

<p><strong>Learn more about our tools:</strong></p>

<ul>
	<li>Shortcodes</li>
	<li>Bootstrap 3</li>
	<li>Media management</li>
	<li>Events</li>
	<li>Blogs</li>
	<li>Portfolio content</li>
</ul>

<p>[button type="primary" link="http://www.sooperthemes.com/minisites/drupal-cms-powerstart-custom"]Get started with CMS Powerstart[/button]</p>

<p>[/column]</p>

<p>[/row]</p>

<p>&nbsp;</p>

<hr>
<p style="text-align: center;">&nbsp;</p>

<h2 style="text-align: center;">Automatic Colored Social Icons</h2>

<p style="text-align: center;">[lead]Supports different icon styles and CSS3 hover animations[/lead]</p>

<p>[social style="square" size="3x" hover_color="auto" hover="disc" Skype="#" Youtube="#" Drupal="#" flickr="#" twitter="#" paypal="#" github="#" linkedin="#" android="#" bitcoin="#"][/social]</p>

<p>&nbsp;</p>

<hr>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'wysiwyg_full',
      ),
    ),
  ),
  'field_page_attachments' => array(),
  'metatags' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'Jurriaan',
  'picture' => 1107,
  'data' => 'b:0;',
  'date' => '2014-12-08 10:35:52 +0100',
);
  return $nodes;
}
